platform :ios, '10.0'
use_frameworks!

def common_pods
    #Networking
    pod 'Alamofire', '~> 4.0'
    #JSON Processing
    pod 'Wrap', '~> 2.1'
    pod 'Unbox', '~> 2.4'
    #Cache images
    pod 'Kingfisher', '~> 4.5.0'
    #Reactive programming
    pod 'RxSwift', '~> 4.0.0'
    pod 'RxCocoa',    '~> 4.0'
end

def ui_pods
    pod 'SVProgressHUD', '~> 2.0'
    pod 'DZNEmptyDataSet', '~> 1.8'
     pod 'SwiftHEXColors', '~> 1.1'
end

target 'MobientoUnsplash' do
    common_pods
    ui_pods
end
